import intf_libs += libcrails%lib{crails}
import intf_libs += libcrails-controllers%lib{crails-controllers}
import intf_libs += libcrails-http-client%lib{crails-http-client}
import intf_libs += libcrails-signin%lib{crails-signin}
import intf_libs += libcrails-semantics%lib{crails-semantics}

lib{crails-oauth}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBCRAILS_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCRAILS_SHARED_BUILD

# Export options.
#
lib{crails-oauth}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{crails-oauth}: cxx.export.poptions += -DLIBCRAILS_STATIC
libs{crails-oauth}: cxx.export.poptions += -DLIBCRAILS_SHARED

if $version.pre_release
  lib{crails-oauth}: bin.lib.version = "-$version.project_id"
else
  lib{crails-oauth}: bin.lib.version = "-$version.major.$version.minor"

{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
